site_name: Panacea
site_url: https://docs.privatechatbot.ai
use_directory_urls: false
site_description: "Collaborative Multi Agentic AI Framework."


# Navigation structure
nav:
  - Introduction: "1_introduction.md"
  - System Architecture:
      - Overview: "2_system_architecture_overview.md"
      - Key Components: "2_key_components.md"
  - Agent Design:
      - Agent Types: "3_agent_types.md"
      - Agent Environment: "3_agent_environment.md"
  - Workflow Management:
      - Task Execution: "4_task_execution.md"
      - Orchestration: "4_orchestration.md"
      - Communication Framework: "5_communication_framework.md"
  - User Interface:
      - Chat-Based Interface: "6_chat_based_interface.md"
      - Agent Creation: "6_agent_creation.md"
  - AI Agent SDK:
    - Overview: api-overview/setup.md
    - Getting Started:
      - Agents: api-overview/agent.md
      - Tasks: api-overview/task.md
      - Crews: api-overview/crews.md
      - Tools: api-overview/tools.md
      - Workflows: api-overview/workflows.md
      - Upload: api-overview/upload.md
      - Fine Tune: api-overview/finetune.md
      - Chat: api-overview/chat.md
      - Evaluate: api-overview/evaluate.md
    - SDK Examples:
      - Defining Agents: api-qa/example1.md
      - Defining Tasks: api-qa/example2.md
      - Building Teams of Agents: api-qa/example3.md
      - Giving Agents Tools: api-qa/example4.md
      - Building Agentic Workflows: api-qa/example5.md
      - Chatting With Predefined Agents: "7_developer_api.md"
    - SDK Use Cases:
      - Financial Analysis: api-usecase/example1.md
      - Event Coordination: api-usecase/example2.md
    - Private SDK:
      - Installation (Private): api-private/installation-private.md
      - Upload (Private): api-private/upload-private.md
      - Chat (Private): api-private/chat-private.md
  - Use Cases:
      - Autonomous AI Coding Agent: "11_autonomous_ai_coding_agent.md"
      - Autonomous AI Sales Agent: "11_autonomous_ai_sales_agent.md"
      - Autonomous AI Job Seeker Agent: "11_autonomous_ai_job_seeker_agent.md"
      - Autonomous Query Agent: "11_autonomous_query_agent.md"
  - Deployment:
      - Local Deployment: "8_local_deployment.md"
      - Private Deployment: "8_private_deployment.md"
  - Logging and Monitoring: "9_logging_and_monitoring.md"
  - Glossary: "10_glossary.md"


extra:
  homepage: https://privatechatbot.ai
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/anote-ai/
    - icon: fontawesome/brands/medium
      link: https://anote-ai.medium.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
  favicon: images/logo.png
  logo: images/logo.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
  - swagger-ui-tag:
      syntaxHighlightTheme: monokai
      tryItOutEnabled: false
      supportedSubmitMethods: []